
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PawsitiveCare
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Surgery
{

    public int SurgeryID { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public System.DateTime SurgeryDate { get; set; }

    public string SurgeryDescription { get; set; }

    public int PetID { get; set; }



    public virtual Pet Pet { get; set; }

}

}
