
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PawsitiveCare
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Weight
{
        
        public int WeightID { get; set; }
        [Display(Name = "Weight")]
        public Nullable<double> Weight1 { get; set; }

    public int PetID { get; set; }
        [Display(Name = "Date Weighed")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
    public Nullable<System.DateTime> WeightDate { get; set; }



    public virtual Pet Pet { get; set; }

}

}
